name: Build Manuals
on: [push]
jobs:
  Build-Manuals:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build BindHelp
        run: |
          svn checkout https://svn.code.sf.net/p/ro-oslib/code/trunk/\!OSLib/Tools oslib-tools
          make -C oslib-tools/BindHelp
      - name: Install ROZipFile 
        run: |
          sudo apt-get install -y python3 python3-pip
          pip install rozipinfo
      - name: Build the manuals
        run: make release
      - name: Save the manuals
        uses: actions/upload-artifact@v2
        with:
          name: stronghelp-manuals
          path: out/